# 断言

# 当这个关键字后边的条件为假的时候，程序自动崩溃并抛出AssertionError的异常

assert 3 > 4
